### ISSUE TITLE
設定変更を押した際にエラーが発生する

### ISSUE THREAD

**Issue by DooignAst** [OrderEats/roadmap#3]
## バグの概要

設定変更を押すと、下記エラーが発生している。

> The server returned a ''405 Method Not Allowed''.

## 再現方法

1.ログインする
2.ヘッダ－のプルダウンより設定変更を押す

## スクリーンショット

<img width="472" alt="スクリーンショット 2020-11-26 23 58 40" src="https://user-images.githubusercontent.com/52205108/100365916-73e10180-3043-11eb-981f-59c3b0a4e16e.png">

**Comment by kai0310** [comment]
@DooignAst 
ありがとう！
元々は設定変更から各種設定を行える計画だったんだけど、今のところその設定項目がないのでリンクのみそのままで残しています。
パスワードは他の方法で変更できるので、氏名やメールアドレスの変更は生徒に行われても困るので。。

こちら設定変更のリンクを削除して対応しようと思います！

---
ただ、業者の方のアカウントに関してはアカウントの設定変更が必要かもしれないので、併せて検討しようと思います。

**Comment by kai0310** [comment]
@DooignAst 
修正しました！確認お願いします

**Comment by DooignAst** [comment]
確認しました！たしかに設定変更のリンクが消え、修正されてました
